# Generated by Django 4.2.4 on 2023-08-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('discription', models.TextField()),
                ('compsition', models.TextField()),
                ('category', models.CharField(choices=[('ML', 'ML'), ('CR', 'CR'), ('LS', 'LS'), ('MS', 'MS'), ('PN', 'PN'), ('GH', 'GH'), ('CZ', 'CZ'), ('IC', 'IC')], max_length=5)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
